### ISSUE TITLE
ModuleNotFoundError: No module named 'scripts.unet'

### ISSUE THREAD

**Issue by bbbdbbb** [FilippoMB/Diffusion_models_tutorial#1]
I run your code on diffusion_from_scratch.ipynb, when I run this "from scripts.unet import SinusoidalPositionEmbeddings",  prompting ModuleNotFoundError: No module named 'scripts.unet'.  Details are as follows：
```
ModuleNotFoundError                       Traceback (most recent call last)
Cell In [29], line 2
      1 # Let's look at how the time embeddings look like
----> 2 from scripts.unet import SinusoidalPositionEmbeddings
      4 time_emb = SinusoidalPositionEmbeddings(100)
      5 t1 = time_emb(torch.tensor([10]))

ModuleNotFoundError: No module named 'scripts.unet'
```
 Thanking you in advance for your support.

**Comment by bbbdbbb** [comment]
I failed in the following attempts ：
```
pip install scripts==1.0
pip install scripts==2.0
pip install scripts.unet
```

**Comment by FilippoMB** [comment]
``scripts`` is a folder, not a package that you can install with pip. The unet file is in the scripts folder: https://github.com/FilippoMB/Diffusion_models_tutorial/blob/main/scripts/unet.py

You have to download the whole project from Github, not just the notebook file.

**Comment by bbbdbbb** [comment]
ohhh，I see, thank you！
